spring:
  data:
    mongodb:
      uri: mongodb+srv://<username>:<password>@cluster0.zrjsm9j.mongodb.net/culinaryCraftDB?retryWrites=true&w=majority
  application:
    name: culinary-craft
server:
  port: 8081
